const express = require("express");
const router = express.Router();
const DiscountController = require("../controllers/DiscountController");
router.get("/", DiscountController.index);
router.get("/add", DiscountController.getAdd);
router.post("/add", DiscountController.postAdd);
router.get("/edit/:id", DiscountController.getEdit);
router.post("/edit/:id", DiscountController.postEdit);
router.post("/remove/:id", DiscountController.remove);
module.exports = router;
